version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install cfn-lint taskcat
  build:
    commands:
      - cfn-lint AWS-Cloudformation-templates/vpc/vpc.yaml
      - cfn-lint AWS-Cloudformation-templates/nat_gateway/natgateway.yaml
      - cfn-lint AWS-Cloudformation-templates/route_table/routetable.yaml
      - cfn-lint AWS-Cloudformation-templates/security_groups/securitygroups.yaml
      - cfn-lint AWS-Cloudformation-templates/ec2_instances/ec2.yaml
      - taskcat test run --config taskcat.yml
