version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install cfn-lint
      - pip install taskcat
  build:
    commands:
      - echo "Running cfn-lint on CloudFormation templates..." 
      - cfn-lint --template vpc.yaml ec2.yaml natgateway.yaml routetable.yaml securitygroups.yaml -i W
      - echo "Running TaskCat tests..."
      - taskcat lint --input-file taskcat.yml
artifacts:
  files:
    - '**/*'
