AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with Public and Private Subnets, Internet Gateway, and Default Security Group

Resources:
  # Create VPC
  Group16VPC:
    Type: 'AWS::EC2::VPC'
    Properties: 
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Group16VPC

  # Create Public Subnet
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref Group16VPC
      CidrBlock: '10.0.1.0/24'
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PublicSubnet

  # Create Private Subnet
  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref Group16VPC
      CidrBlock: '10.0.2.0/24'
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet

  # Create Internet Gateway
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: 
      Tags:
        - Key: Name
          Value: InternetGateway

  # Attach Internet Gateway to VPC
  AttachInternetGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref Group16VPC
      InternetGatewayId: !Ref InternetGateway
  DefaultSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Default Security Group with Default Rules
      VpcId: !Ref Group16VPC 
      SecurityGroupIngress:
        - IpProtocol: '-1'  
          FromPort: 0
          ToPort: 65535
          CidrIp: '0.0.0.0/0'  
      SecurityGroupEgress:
        - IpProtocol: '-1'  
          FromPort: 0
          ToPort: 65535
          CidrIp: '0.0.0.0/0'  
Outputs:
  VPCId:
    Description: ID of the VPC
    Value: !Ref Group16VPC
    Export:
      Name: Group16VPCId

  InternetGatewayId:
    Description: ID of the Internet Gateway
    Value: !Ref InternetGateway
    Export:
      Name: Group16InternetGatewayId

  PublicSubnetId:
    Description: ID of the Public Subnet
    Value: !Ref PublicSubnet
    Export:
      Name: Group16PublicSubnetId

  PrivateSubnetId:
    Description: ID of the Private Subnet
    Value: !Ref PrivateSubnet
    Export:
      Name: Group16PrivateSubnetId
  DefaultSecurityGroupId:
    Description: ID of the Custom Security Group
    Value: !Ref DefaultSecurityGroup
    Export:
      Name: Group16DefaultSecurityGroupId
