AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with Public and Private Subnets, Internet Gateway, and Default Security Group

Resources:
  # Create VPC
  Group16VPC:
    Type: 'AWS::EC2::VPC'
    Properties: 
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Group16VPC


  # Create Internet Gateway
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: 
      Tags:
        - Key: Name
          Value: Group16InternetGateway

  # Attach Internet Gateway to VPC
  AttachInternetGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref Group16VPC
      InternetGatewayId: !Ref InternetGateway


Outputs:
  VPCId:
    Description: ID of the VPC
    Value: !Ref Group16VPC
    Export:
      Name: Group16VPCId
  InternetGatewayId:
    Description: ID of the Internet Gateway
    Value: !Ref Group16InternetGateway
    Export:
      Name: Group16InternetGatewayId
